# Generated by Django 3.2 on 2022-12-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_account_credit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.AlterModelTable(
            name='credit',
            table='Loans',
        ),
    ]
