# Generated by Django 3.2 on 2022-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_alter_account_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='work_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
