# Generated by Django 3.2 on 2022-12-06 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_client_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
