# Generated by Django 3.2 on 2022-12-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Акаунт', 'verbose_name_plural': 'Акаунты'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': 'Кредит', 'verbose_name_plural': 'Кредиты'},
        ),
    ]
