# Generated by Django 3.2 on 2022-12-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_auto_20221206_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
